["component:reader"]
component_to_shim = "docs:writetwo"
interface_to_shim = "writer"
package_shim = "docs:writershim"


["component:file"]
component_to_shim = "docs:writetwo"
interface_to_shim = "writer"
package_shim = "shim:writershim"


["component:filereading"]
component_to_shim = "docs:writeing"
interface_to_shim = "reader"
package_shim = "docs:readershim"