// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod component {
        pub mod trustedwriter {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod writer {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_writing_back_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    T::writing_back(_rt::Vec::from_raw_parts(arg0.cast(), len0, len0));
                }
                pub trait Guest {
                    fn writing_back(info: _rt::Vec<u8>) -> ();
                }
                #[doc(hidden)]
                macro_rules! __export_component_trustedwriter_writer_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "component:trustedwriter/writer#writing-back")] unsafe extern "C"
                        fn export_writing_back(arg0 : * mut u8, arg1 : usize,) { unsafe {
                        $($path_to_types)*:: _export_writing_back_cabi::<$ty > (arg0,
                        arg1) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_component_trustedwriter_writer_cabi;
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_trustedwriter_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::component::trustedwriter::writer::__export_component_trustedwriter_writer_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::component::trustedwriter::writer);
    };
}
#[doc(inline)]
pub(crate) use __export_trustedwriter_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:component:trustedwriter:trustedwriter:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 248] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07u\x01A\x02\x01A\x02\x01\
B\x03\x01p}\x01@\x01\x04info\0\x01\0\x04\0\x0cwriting-back\x01\x01\x04\0\x1ecomp\
onent:trustedwriter/writer\x05\0\x04\0%component:trustedwriter/trustedwriter\x04\
\0\x0b\x13\x01\0\x0dtrustedwriter\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\
\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
