// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod docs {
    pub mod writetwo {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod writer {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            #[allow(unused_unsafe, clippy::all)]
            pub fn writing_back(info: &[u8]) -> () {
                unsafe {
                    let vec0 = info;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "docs:writetwo/writer")]
                    unsafe extern "C" {
                        #[link_name = "writing-back"]
                        fn wit_import1(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0) };
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod docs {
        pub mod writetwo {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod writer {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_writing_back_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    T::writing_back(_rt::Vec::from_raw_parts(arg0.cast(), len0, len0));
                }
                pub trait Guest {
                    fn writing_back(info: _rt::Vec<u8>) -> ();
                }
                #[doc(hidden)]
                macro_rules! __export_docs_writetwo_writer_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "docs:writetwo/writer#writing-back")] unsafe extern "C" fn
                        export_writing_back(arg0 : * mut u8, arg1 : usize,) { unsafe {
                        $($path_to_types)*:: _export_writing_back_cabi::<$ty > (arg0,
                        arg1) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_docs_writetwo_writer_cabi;
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_writershim_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::docs::writetwo::writer::__export_docs_writetwo_writer_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::docs::writetwo::writer);
    };
}
#[doc(inline)]
pub(crate) use __export_writershim_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:shim:writershim:writershim:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 284] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x9b\x01\x01A\x02\x01\
A\x04\x01B\x03\x01p}\x01@\x01\x04info\0\x01\0\x04\0\x0cwriting-back\x01\x01\x03\0\
\x14docs:writetwo/writer\x05\0\x01B\x03\x01p}\x01@\x01\x04info\0\x01\0\x04\0\x0c\
writing-back\x01\x01\x04\0\x14docs:writetwo/writer\x05\x01\x04\0\x1ashim:writers\
him/writershim\x04\0\x0b\x10\x01\0\x0awritershim\x03\0\0\0G\x09producers\x01\x0c\
processed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
