[package]
name = "trusted"
version = "0.1.0"
edition = "2024"

[dependencies]
wit-bindgen-rt = { version = "0.44.0", features = ["bitflags"] }
wasi = "0.13.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:trusted"

[package.metadata.component.dependencies]



[package.metadata.component.target.dependencies]
"component:splitwrite" = { path = "..\\trustedwriter\\wit" }
"component:norf" = { path = "..\\fileloader\\wit" }
"wasi:cli" = "0.2.x"
"wasi:io" = "0.2.7"